spring:
  profiles:
    active: h2 # postgresql or h2
  application:
    name: Dev Test

server:
  port: 4000
  shutdown: "graceful"

# If you want to use a database then uncomment the `group:, readiness: and include: "db"`
# lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: info # should we have more?

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers

  # Optional: make OpenAPI output more stable / git-friendly
  writer-with-order-by-keys: true

  # Nice UI improvements
  swagger-ui:
    path: /swagger-ui.html                                # default anyway, but explicit is fine
    operationsSorter: alpha                               # sort operations inside each tag alphabetically
    tagsSorter: alpha                                     # sort tags alphabetically
    tryItOutEnabled: true                                 # show "Try it out" expanded by default

  # Optional: give your API a proper title/description/version
  info:
    title:      "DEV API"
    description: "Development APIs for [project/module name]"
    version:    ${project.version}
